from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy

from . import api_v2_views, api_views, views
from .forms import PasswordResetConfirmForm, PasswordResetRequestForm

app_name = "store"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("account/", views.AccountLoginView.as_view(), name="login"),
    path(
        "account/password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset_form.html",
            email_template_name="emails/password_reset_email.txt",
            subject_template_name="emails/password_reset_subject.txt",
            form_class=PasswordResetRequestForm,
            success_url=reverse_lazy("store:password-reset-done"),
        ),
        name="password-reset",
    ),
    path(
        "account/password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html",
        ),
        name="password-reset-done",
    ),
    path(
        "account/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html",
            form_class=PasswordResetConfirmForm,
            success_url=reverse_lazy("store:password-reset-complete"),
        ),
        name="password-reset-confirm",
    ),
    path(
        "account/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html",
        ),
        name="password-reset-complete",
    ),
    path("dashboard/", views.AccountDashboardView.as_view(), name="account-dashboard"),
    path("dashboard/settings/", views.AccountSettingsView.as_view(), name="account-settings"),
    path("dashboard/settings/profile/", views.AccountProfileUpdateView.as_view(), name="account-profile-update"),
    path("dashboard/settings/password/", views.AccountPasswordChangeView.as_view(), name="account-password-change"),
    path("dashboard/settings/addresses/", views.AccountAddressUpsertView.as_view(), name="account-address-add"),
    path("dashboard/settings/addresses/<int:address_id>/edit/", views.AccountAddressUpsertView.as_view(), name="account-address-edit"),
    path("dashboard/settings/addresses/<int:address_id>/delete/", views.AccountAddressDeleteView.as_view(), name="account-address-delete"),
    path("dashboard/settings/addresses/<int:address_id>/default/", views.AccountAddressDefaultView.as_view(), name="account-address-default"),
    path("operations/overview/", views.OperationsDashboardView.as_view(), name="operations-dashboard"),
    path("operations/inventory/", views.InventoryDashboardView.as_view(), name="inventory-dashboard"),
    path("operations/inventory/adjustments/", views.InventoryAdjustmentView.as_view(), name="inventory-adjustment"),
    path("operations/inventory/transfers/", views.InventoryTransferView.as_view(), name="inventory-transfer"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("account/verify/<str:token>/", views.VerifyEmailView.as_view(), name="verify-email"),
    path("account/verify/resend/", views.ResendVerificationEmailView.as_view(), name="resend-verification-email"),
    path("logout/", views.logout_view, name="logout"),
    path("products/", views.CatalogView.as_view(), name="catalog"),
    path("products<int:page_number>/", views.legacy_products_page, name="legacy-products-page"),
    path("products/<slug:slug>/", views.ProductDetailView.as_view(), name="product-detail"),
    path("products/<slug:slug>/review/", views.SubmitReviewView.as_view(), name="submit-review"),
    path("products/<slug:slug>/compare/", views.ToggleCompareView.as_view(), name="toggle-compare"),
    path("productdetail/", views.legacy_product_detail_redirect, name="productdetail"),
    path("productdetail/<slug:slug>/", views.ProductDetailView.as_view(), name="productdetail-slug"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/apply-coupon/", views.ApplyCouponView.as_view(), name="apply-coupon"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("checkout/success/", views.StripeCheckoutSuccessView.as_view(), name="payment-success"),
    path("checkout/cancel/<str:reference>/", views.StripeCheckoutCancelView.as_view(), name="payment-cancel"),
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("wishlist/", views.WishlistView.as_view(), name="wishlist"),
    path("wishlist/toggle/<slug:slug>/", views.ToggleWishlistView.as_view(), name="toggle-wishlist"),
    path("insights/", views.InsightsView.as_view(), name="insights"),
    path("orders/", views.OrderHistoryView.as_view(), name="order-history"),
    path("orders/<str:reference>/items/<int:order_item_id>/return/", views.ReturnRequestCreateView.as_view(), name="return-request"),
    path("support/threads/", views.SupportInboxView.as_view(), name="support-threads"),
    path("support/threads/<int:thread_id>/", views.SupportThreadDetailView.as_view(), name="support-thread-detail"),
    path("support/threads/<int:thread_id>/resolve/", views.ResolveSupportThreadView.as_view(), name="support-thread-resolve"),
    path("cart/add/<slug:slug>/", views.AddToCartView.as_view(), name="add-to-cart"),
    path("cart/remove/<slug:slug>/", views.RemoveFromCartView.as_view(), name="remove-from-cart"),
    path("cart/decrease/<slug:slug>/", views.DecreaseCartItemView.as_view(), name="decrease-cart-item"),
    path("health/", views.health_check, name="health"),
    path("webhooks/stripe/", views.stripe_webhook, name="stripe-webhook"),
    path("api/v1/", api_views.api_root, name="api-root"),
    path("api/v1/catalog/", api_views.api_catalog, name="api-catalog"),
    path("api/v1/catalog/<slug:slug>/", api_views.api_product_detail, name="api-product-detail"),
    path("api/v1/recommendations/<slug:slug>/", api_views.api_recommendations, name="api-recommendations"),
    path("api/v1/compare/", api_views.api_compare_state, name="api-compare"),
    path("api/v1/analytics/overview/", api_views.api_analytics_overview, name="api-analytics-overview"),
    path("api/v1/account/overview/", api_views.api_account_overview, name="api-account-overview"),
    path("api/v1/account/security/", api_views.api_account_security, name="api-account-security"),
    path("api/v1/intelligence/assistant/", api_views.api_ai_assistant, name="api-ai-assistant"),
    path("api/v1/health/", api_views.api_health, name="api-health"),
    path("api/v1/orders/<str:reference>/", api_views.api_order_tracking, name="api-order-tracking"),
    path("api/v1/support/threads/", api_views.api_support_threads, name="api-support-threads"),
    path("api/v1/support/threads/<int:thread_id>/", api_views.api_support_thread_detail, name="api-support-thread-detail"),
    path("api/v1/wishlist/<slug:slug>/toggle/", api_views.api_wishlist_toggle, name="api-wishlist-toggle"),
    path("api/v2/", api_v2_views.ApiV2RootView.as_view(), name="api-v2-root"),
    path("api/v2/catalog/", api_v2_views.CatalogListV2View.as_view(), name="api-v2-catalog"),
    path("api/v2/auth/token/", api_v2_views.ApiTokenV2View.as_view(), name="api-v2-auth-token"),
    path("api/v2/account/profile/", api_v2_views.AccountProfileV2View.as_view(), name="api-v2-account-profile"),
    path("api/v2/account/security/", api_v2_views.AccountSecurityV2View.as_view(), name="api-v2-account-security"),
    path("api/v2/account/access/", api_v2_views.AccountAccessV2View.as_view(), name="api-v2-account-access"),
    path("api/v2/account/password/", api_v2_views.AccountPasswordV2View.as_view(), name="api-v2-account-password"),
    path("api/v2/account/addresses/", api_v2_views.AddressListCreateV2View.as_view(), name="api-v2-account-addresses"),
    path("api/v2/account/addresses/<int:address_id>/", api_v2_views.AddressDetailV2View.as_view(), name="api-v2-account-address-detail"),
    path("api/v2/account/addresses/<int:address_id>/default/", api_v2_views.AddressDefaultV2View.as_view(), name="api-v2-account-address-default"),
    path("api/v2/orders/<str:reference>/reservations/", api_v2_views.OrderReservationsV2View.as_view(), name="api-v2-order-reservations"),
    path("api/v2/inventory/overview/", api_v2_views.InventoryOverviewV2View.as_view(), name="api-v2-inventory-overview"),
    path("api/v2/inventory/warehouses/", api_v2_views.InventoryWarehousesV2View.as_view(), name="api-v2-inventory-warehouses"),
    path("api/v2/inventory/reservations/active/", api_v2_views.InventoryActiveReservationsV2View.as_view(), name="api-v2-inventory-active-reservations"),
    path("api/v2/inventory/movements/", api_v2_views.InventoryMovementsV2View.as_view(), name="api-v2-inventory-movements"),
    path("api/v2/inventory/adjustments/", api_v2_views.InventoryAdjustmentV2View.as_view(), name="api-v2-inventory-adjustments"),
    path("api/v2/inventory/transfers/", api_v2_views.InventoryTransferV2View.as_view(), name="api-v2-inventory-transfers"),
]
