from django.urls import path

from . import api_views, views

app_name = "store"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("account/", views.AccountLoginView.as_view(), name="login"),
    path("dashboard/", views.AccountDashboardView.as_view(), name="account-dashboard"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("account/verify/<str:token>/", views.VerifyEmailView.as_view(), name="verify-email"),
    path("account/verify/resend/", views.ResendVerificationEmailView.as_view(), name="resend-verification-email"),
    path("logout/", views.logout_view, name="logout"),
    path("products/", views.CatalogView.as_view(), name="catalog"),
    path("products<int:page_number>/", views.legacy_products_page, name="legacy-products-page"),
    path("products/<slug:slug>/", views.ProductDetailView.as_view(), name="product-detail"),
    path("products/<slug:slug>/review/", views.SubmitReviewView.as_view(), name="submit-review"),
    path("products/<slug:slug>/compare/", views.ToggleCompareView.as_view(), name="toggle-compare"),
    path("productdetail/", views.legacy_product_detail_redirect, name="productdetail"),
    path("productdetail/<slug:slug>/", views.ProductDetailView.as_view(), name="productdetail-slug"),
    path("cart/", views.CartView.as_view(), name="cart"),
    path("cart/apply-coupon/", views.ApplyCouponView.as_view(), name="apply-coupon"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("checkout/success/", views.StripeCheckoutSuccessView.as_view(), name="payment-success"),
    path("checkout/cancel/<str:reference>/", views.StripeCheckoutCancelView.as_view(), name="payment-cancel"),
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("wishlist/", views.WishlistView.as_view(), name="wishlist"),
    path("wishlist/toggle/<slug:slug>/", views.ToggleWishlistView.as_view(), name="toggle-wishlist"),
    path("insights/", views.InsightsView.as_view(), name="insights"),
    path("orders/", views.OrderHistoryView.as_view(), name="order-history"),
    path("orders/<str:reference>/items/<int:order_item_id>/return/", views.ReturnRequestCreateView.as_view(), name="return-request"),
    path("support/threads/", views.SupportInboxView.as_view(), name="support-threads"),
    path("support/threads/<int:thread_id>/", views.SupportThreadDetailView.as_view(), name="support-thread-detail"),
    path("support/threads/<int:thread_id>/resolve/", views.ResolveSupportThreadView.as_view(), name="support-thread-resolve"),
    path("cart/add/<slug:slug>/", views.AddToCartView.as_view(), name="add-to-cart"),
    path("cart/remove/<slug:slug>/", views.RemoveFromCartView.as_view(), name="remove-from-cart"),
    path("cart/decrease/<slug:slug>/", views.DecreaseCartItemView.as_view(), name="decrease-cart-item"),
    path("health/", views.health_check, name="health"),
    path("webhooks/stripe/", views.stripe_webhook, name="stripe-webhook"),
    path("api/v1/", api_views.api_root, name="api-root"),
    path("api/v1/catalog/", api_views.api_catalog, name="api-catalog"),
    path("api/v1/catalog/<slug:slug>/", api_views.api_product_detail, name="api-product-detail"),
    path("api/v1/recommendations/<slug:slug>/", api_views.api_recommendations, name="api-recommendations"),
    path("api/v1/compare/", api_views.api_compare_state, name="api-compare"),
    path("api/v1/analytics/overview/", api_views.api_analytics_overview, name="api-analytics-overview"),
    path("api/v1/account/overview/", api_views.api_account_overview, name="api-account-overview"),
    path("api/v1/account/security/", api_views.api_account_security, name="api-account-security"),
    path("api/v1/intelligence/assistant/", api_views.api_ai_assistant, name="api-ai-assistant"),
    path("api/v1/health/", api_views.api_health, name="api-health"),
    path("api/v1/orders/<str:reference>/", api_views.api_order_tracking, name="api-order-tracking"),
    path("api/v1/support/threads/", api_views.api_support_threads, name="api-support-threads"),
    path("api/v1/support/threads/<int:thread_id>/", api_views.api_support_thread_detail, name="api-support-thread-detail"),
    path("api/v1/wishlist/<slug:slug>/toggle/", api_views.api_wishlist_toggle, name="api-wishlist-toggle"),
]
