# Generated by Django 6.0.3 on 2026-04-06 17:09

from django.db import migrations, models


def backfill_payment_metadata(apps, schema_editor):
    Order = apps.get_model("dokan", "Order")

    for order in Order.objects.exclude(status="cart"):
        payment_provider = "stripe" if order.payment_method == "stripe_checkout" else "manual"
        if order.status == "delivered":
            payment_status = "paid"
            paid_at = order.placed_at
        elif order.status in {"placed", "processing", "shipped", "payment_pending"}:
            payment_status = "pending"
            paid_at = None
        else:
            payment_status = "unpaid"
            paid_at = None

        order.payment_provider = payment_provider
        order.payment_status = payment_status
        order.paid_at = paid_at
        order.coupon_usage_recorded = bool(
            order.coupon_id and order.status not in {"cart", "payment_pending"}
        )
        order.save(
            update_fields=[
                "payment_provider",
                "payment_status",
                "paid_at",
                "coupon_usage_recorded",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0004_seed_advanced_store_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_usage_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on delivery'), ('card_on_delivery', 'Card on delivery'), ('bank_transfer', 'Bank transfer'), ('stripe_checkout', 'Stripe Checkout')], default='cash_on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('payment_pending', 'Payment Pending'), ('placed', 'Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('payment_pending', 'Payment Pending'), ('placed', 'Placed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.RunPython(backfill_payment_metadata, migrations.RunPython.noop),
    ]
