# Generated by Django 6.0.3 on 2026-04-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dokan", "0007_customerprofile_loginactivity_supportthread_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_operations_dashboard", "Can view store operations dashboard"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="supportthread",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "permissions": [
                    ("manage_support_threads", "Can manage all support threads"),
                ],
            },
        ),
    ]
