# Generated by Django 6.0.3 on 2026-04-08 06:42

import django.db.models.deletion
from django.db import migrations, models


def seed_default_warehouse_and_stock_levels(apps, schema_editor):
    Warehouse = apps.get_model("dokan", "Warehouse")
    Item = apps.get_model("dokan", "Item")
    StockLevel = apps.get_model("dokan", "StockLevel")

    warehouse, _ = Warehouse.objects.get_or_create(
        code="CENTRAL",
        defaults={
            "name": "Central Fulfillment Center",
            "city": "Kathmandu",
            "state": "Bagmati",
            "country": "Nepal",
            "priority": 1,
            "is_active": True,
        },
    )

    for item in Item.objects.all().only("id", "stock", "reorder_level"):
        if not StockLevel.objects.filter(item=item).exists():
            StockLevel.objects.create(
                warehouse=warehouse,
                item=item,
                on_hand=item.stock,
                reserved=0,
                safety_stock=item.reorder_level,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0008_add_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
                'permissions': [('manage_inventory_network', 'Can manage warehouses and stock network'), ('view_inventory_dashboard', 'Can view inventory dashboard')],
            },
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['user__username'], 'permissions': [('manage_customer_accounts', 'Can manage customer accounts')]},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='dokan.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='dokan.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='dokan.orderitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='dokan.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('manage_stock_reservations', 'Can manage inventory reservations')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.PositiveIntegerField(default=0)),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='dokan.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='dokan.warehouse')),
            ],
            options={
                'ordering': ['warehouse__priority', 'warehouse__name', 'item__title'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'item'), name='unique_stock_level_per_warehouse_item')],
            },
        ),
        migrations.RunPython(
            seed_default_warehouse_and_stock_levels,
            noop_reverse,
        ),
    ]
