# Generated by Django 4.1.4 on 2026-04-08 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dokan', '0009_warehouse_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='html_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='text_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='primary_image_file',
            field=models.ImageField(blank=True, upload_to='products/primary/%Y/%m'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('adjustment_in', 'Adjustment in'), ('adjustment_out', 'Adjustment out'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('reservation_hold', 'Reservation hold'), ('reservation_release', 'Reservation release'), ('fulfillment', 'Fulfillment'), ('return_restock', 'Return restock')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('on_hand_delta', models.IntegerField(default=0)),
                ('reserved_delta', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='dokan.item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='dokan.order')),
                ('related_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_stock_movements', to='dokan.warehouse')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='dokan.inventoryreservation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='dokan.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='dokan.item')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
