# Generated by Django 4.1.4 on 2026-07-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0013_prefer_same_category_gallery_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
