# Generated by Django 4.1.4 on 2026-07-06 09:03

from django.db import migrations, models
import dokan.models


class Migration(migrations.Migration):

    dependencies = [
        ('dokan', '0017_fix_electronics_images_with_no_matching_stock_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='primary_image_file',
            field=models.ImageField(blank=True, upload_to='products/primary/%Y/%m', validators=[dokan.models.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/%Y/%m', validators=[dokan.models.validate_image_file_size]),
        ),
    ]
